# Condor Submit File
# bayes_hfs analysis of IRAM data

ODIR = osdf:///ospool/ap40/data/trey.wenger
DIR = /home/trey.wenger/cno_ratios_analysis

# Container
container_image = $(ODIR)/bayes_hfs_v1.1.4.sif

# Executable
executable = $(DIR)/condor/run_fit_iram.sh
arguments = $(source) $(n)

# Data handling
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(DIR)/scripts/fit_iram.py,$(DIR)/data/bayes_hfs_priors.txt,$(DIR)/data/mol_data_12CN.pkl,$(DIR)/data/mol_data_13CN.pkl,$(DIR)/data/mol_metadata_12CN.pkl,$(DIR)/data/mol_metadata_13CN.pkl,$(DIR)/data/107-23.tar.gz,$(DIR)/data/042-25.tar.gz
transfer_output_remaps = "$(source)_n$(n)_results.pkl = $(ODIR)/results/$(out)/$(source)_n$(n)_results.pkl"

# Logging
log = $(DIR)/logs/$(out)/iram_$(Cluster)_$(Process).log
error = $(DIR)/logs/$(out)/iram_$(Cluster)_$(Process).err
output = $(DIR)/logs/$(out)/iram_$(Cluster)_$(Process).out
stream_output = False
stream_error = False

# Resource request
request_cpus = 8
request_memory = 24GB
request_disk = 24GB
+JobDurationCategory = "Long"

queue source from $(DIR)/data/all_sources.txt